### PR TITLE
feat: initial storybook integration 🐿 v2.13.0

### PR DESCRIPTION
**Pull request by alexnaish**
### Description

I've been meaning to do this for a while and had an hour this morning as I was blocked on another ticket. I've added a fair few stories for the different components as a base for the other components.

This should make it a lot easier to develop, having no reliance on a custom demo server. 

So far I've got:

- [x] Loading of all NCF styles via main SCSS export
- [x] Automatic discovery of component properties
- [x] Accessibility checks
- [ ] Automatic deployment upon release to Github pages

General Overview:

Screenshot 2020-08-17 at 12 58 28

Accessibility view:

Screenshot 2020-08-17 at 12 58 40

Prop discovery

Screenshot 2020-08-17 at 12 58 52

### CODE REVIEW

**Comment by nickramsbottom** [comment]
This is incredibly cool!

**Comment by alexnaish** [comment]
I think we should merge it in as past of the new major release - post https://github.com/Financial-Times/n-conversion-forms/pull/439. Whats your thoughts?

**Comment by nickramsbottom** [comment]
@alexnaish Strong agree! @Financial-Times/acquisition any thoughts on this?

**Comment by alexnaish** [comment]
Closing as its part of the main v16 branch!

**Pull request closed without merging**
