### PR TITLE
Fix the check for the email exists check since the response has changed

### PR DESCRIPTION
**Pull request by remybach**
🐿 v2.10.3

## Feature Description

The SDK response now just returns `true` or `false`.

### CODE REVIEW

**Comment by remybach** [comment]
It did when I tried to hook this all up locally just now. Is that correct @CourtneyLO?

**Comment by liamkeaton** [comment]
The SDK now returns just boolean, not sure what the `next-subscribe` wrapper will return

**Comment by remybach** [comment]
The wrapper in `next-subscribe` is just a very thin proxy and returns exactly what the SDK returns.

**Comment by liamkeaton** [comment]
Is `true` a valid `application/json` response?

**Pull request merged**
