### PR TITLE
ACQ-1623: change helpers to match new checkout gateway and 3ds challenge

### PR DESCRIPTION
**Pull request by ludrob**
### Description
Updated helpers to handle checkout as payment gateway
We are no longer using Worldpay but Checkout as a gateway provider on test.
So we now need to change the card number..
I've also added convenience button for the 3ds challenge.

US uses chase, which has different test cards.
Messed around with the styles a bit to reduce padding and fit more stuff.

BEFORE MERGING: check with accounts team if they use this and fine with changes (I'm not sure which gateway they are on right now)

### Ticket
https://financialtimes.atlassian.net/browse/ACQ-1623

### Screenshots

| Before | After |
| ------ | ----- |
|        |       |

### Reminder
Have you completed these common tasks (remove those that don't apply)?

- [ ] **Documentation** updated or created
- [ ] **Tests** written for new or updated for existing functionality
- [ ] **Stories** updated to use this change
- [ ] **Accessibility** checked for screen readers and contrast
- [ ] **Design Review** ran past the designer
- [ ] **Product Review** ran past the product owner

### CODE REVIEW

**Comment by ludrob** [comment]
> @ludrob you are romving `package-lock.json`. is that ok?

no it's not, good spot! I'll add it back.

**Comment by ludrob** [comment]
> > @ludrob you are romving `package-lock.json`. is that ok?
> 
> no it's not, good spot! I'll add it back.

done https://github.com/Financial-Times/n-conversion-forms/pull/637/commits/6c7fbfa52993c0081e94082b7315da4903aa1d7e

**Comment by ekocian** [comment]
> > > @ludrob you are romving `package-lock.json`. is that ok?
> > 
> > 
> > no it's not, good spot! I'll add it back.
> 
> done [6c7fbfa](https://github.com/Financial-Times/n-conversion-forms/commit/6c7fbfa52993c0081e94082b7315da4903aa1d7e)

I see it still there

**Comment by ludrob** [comment]
> > > > @ludrob you are romving `package-lock.json`. is that ok?
> > > 
> > > 
> > > no it's not, good spot! I'll add it back.
> > 
> > 
> > done [6c7fbfa](https://github.com/Financial-Times/n-conversion-forms/commit/6c7fbfa52993c0081e94082b7315da4903aa1d7e)
> 
> I see it still there

Not sure what you mean.
I initially deleted it by accident in https://github.com/Financial-Times/n-conversion-forms/pull/637/commits/93eebc0fe9d969e907d35b72d88f0d34c50d99c6, and it's now back with https://github.com/Financial-Times/n-conversion-forms/pull/637/commits/6c7fbfa52993c0081e94082b7315da4903aa1d7e

So that all good?

**Review by joejeet — APPROVED** [review]

**Comment by joejeet** [comment]
NB comment: what is debug stories component used for?

**Review by jorbuedo — APPROVED** [review]

**Comment by ludrob** [comment]
> NB comment: what is debug stories component used for?

That's so that we can play with the debug helpers in storybook
image

**Pull request merged**
