### PR TITLE
Export all components from files

### PR DESCRIPTION
**Pull request by liamkeaton**
Use export instead of importing and exporting later to reduce
duplication and reduce instances of merge conflicts.

### CODE REVIEW

**Comment by ludrob** [comment]
I was tempted to do that, the reason I didn't is that you no longer have a nice list of all the available component names in one place.
What about `export * as Name from ...`?
Would that work?

**Comment by liamkeaton** [comment]
@ludrob we would have to do `export { Name } from './file';` as we have named exports. 

I would prefer not too as it's another instance of the class name to update and something that's very easy to forget.

**Comment by ludrob** [comment]
> @ludrob we would have to do `export { Name } from './file';` as we have named exports.
> 
> I would prefer not too as it's another instance of the class name to update and something that's very easy to forget.

I know and I agree. Just want to make this easy to use. 
We only import from index.js so far, both in next-profile and the demo (and right now: not in tests so you could miss it but that can be changed).
I find it quite handy to be able to just pull the index.js and know what I can use, without looking at the list of components, one less mental step.
I personally think we don't change the component names often. and would rather have something easier to use but it definitely is in the land of personal preference.

Unless someone else objects, ignore me :)

**Comment by liamkeaton** [comment]
@umbobabo final word?

**Comment by liamkeaton** [comment]
Components can be exported explicitly later if needed

**Pull request merged**
