### PR TITLE
UG-207: Add custom B2C payment term component

### PR DESCRIPTION
**Pull request by davidbailey00**
### Description
Add a new payment term component for B2C partnerships with custom terms.

See also Financial-Times/next-subscribe#1255

[UG-207](https://financialtimes.atlassian.net/browse/UG-207)

### Screenshots

A custom payment component with the title Digital FT + The Washington Post

### Reminder
Have you completed these common tasks (remove those that don't apply)?

- [x] **Documentation** updated or created (Storybook (but isn't showing up?))
- [x] **Tests** written for new or updated for existing functionality
- [x] **Stories** updated to use this change
- [x] **Accessibility** checked for screen readers and contrast
- [ ] ~~**Design Review** ran past the designer~~ not released live yet - waiting for our designer to finish vacation
- [x] **Product Review** ran past the product owner

### CODE REVIEW

**Review by nickramsbottom — APPROVED** [review]
Nice 🔥

**Review by jenniferemshepherd — APPROVED** [review]

**Comment by nickramsbottom** [comment]
Would it be possible to add this to the storybook?

**Comment by davidbailey00** [comment]
@nickramsbottom I've added a `.stories.js` file so this is already in SB - do you want me to deploy the `gh-pages` branch after merging or is this automatic?

**Comment by nickramsbottom** [comment]
@davidbailey00  Ohhhh nice, didn't notice the `stories.js` file. Thank you for doing that!

**Pull request merged**
